version: "3.3"

services:
  portainer:
    image: portainer/portainer
    restart: "always"
    container_name: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/portainer:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"